### ISSUE TITLE
Upgrade to Vue.js v3 (OSOE-338)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Orchard-Vue.js#38]
Once Orchard does that too, see: https://github.com/OrchardCMS/OrchardCore/issues/7110 

Also see [the official migration guide](https://v3-migration.vuejs.org/).

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-338)

**Comment by Piedone** [comment]
Can't we feasibly do this without waiting for OC @sarahelsaig?

**Comment by sarahelsaig** [comment]
I think it's possible. The thing to avoid is importing Vue2 and Vue3 on the same page the old fashioned way, because both export the `Vue` global variable. If the app is instantiated from our `<vue-component-app>` tag helper then we turns its script into an ES module so Vue is imported locally to the module instead of globally. We can also write a migration guide on how to do the same for those who can't use the tag helper.

btw you linked the migration guide for VueX. Here is the official migration guide for Vue: https://v3-migration.vuejs.org/

**Comment by Piedone** [comment]
OK then, thank you. On the frontend, this should not be an issue.

Because this might be necessary for a project of ours soon.

**Comment by sarahelsaig** [comment]
How soon? I'd gladly take on this issue. So if you have a rough idea when it will be needed I can plan accordingly.

**Comment by Piedone** [comment]
Actually, this might be needed ASAP, I'll share some non-public details privately.

**Comment by Piedone** [comment]
Also, we should check if we still need `VueContentSecurityPolicyProvider` after this upgrade.
